# -- Site Configuration --
# Refer to the theme docs for more details about each of these parameters.
# https://jpanther.github.io/congo/docs/getting-started/

# baseURL = "https://your_domain.com/"
defaultContentLanguage = "en"

hasCJKLanguage = true

enableRobotsTXT = true
summaryLength = 200

[outputs]
  home = ["HTML", "RSS", "JSON"]

[pagination]
  pagerSize = 10

theme = "congo"