languageCode = "en"
languageName = "English"
languageDirection = "ltr"
weight = 1

title = "蒋大培的博客"

[params]
  dateFormat = "2 January 2006"

  # mainSections = ["section1", "section2"]
  description = "My awesome website"

[params.author]
  name = "蒋大培"
  image = "img/author.jpg"
  headline = "aijishu"
  bio = "A little bit about you"
  links = [
    { email = "mailto:hello@your_domain.com" },
    { github = "https://github.com/username" },
    { twitch = "https://twitch.tv/username" },
    { x-twitter = "https://twitter.com/username" },
    { youtube = "https://youtube.com/username" },
  ]
