# -- Main Menu --
# The main menu is displayed in the header at the top of the page.
# Acceptable parameters are name, pageRef, page, url, title, weight.

[[main]]
  name = "关于"
  pageRef = "about"
  weight = 10

[[main]]
  name = "文章"
  pageRef = "writings"
  weight = 20

[[main]]
  name = "项目"
  pageRef = "projects"
  weight = 30

[[main]]
  identifier = "search"
  weight = 99
  [main.params]
    action = "search"

[[main]]
  identifier = "locale"
  weight = 100
  [main.params]
    action = "locale"

# -- Footer Menu --
# The footer menu is displayed at the bottom of the page, just before
# the copyright notice. Configure as per the main menu above.

[[footer]]
  name = "标签"
  pageRef = "tags"
  weight = 10

[[footer]]
  name = "归档"
  pageRef = "archives"
  weight = 20
